### ISSUE TITLE
color sequences should not be written to regular files

### ISSUE THREAD

**Issue by wrp** [jhasse/clicolors#16]
Perhaps this is an editorial discussion on the current wording of the document.  Currently, the doc states: "ANSI colors are supported and should be used when the program isn’t piped.", but the sample code implements: "ANSI colors are supported and should be used when the program's output is to a terminal".  The sample code is correct in the sense that it implements the desired behavior.  When a program is writing output to a regular file it "isn't piped", but it should not emit color sequences. 

The text should be edited to match the sample implementation.

**Comment by jhasse** [comment]
Good point, feel free to create a PR.
