### ISSUE TITLE
Add reference to NO_COLOR

### ISSUE THREAD

**Issue by twpayne** [jhasse/clicolors#7]
https://no-color.org/ has different, but related, goals. Maybe add a link or description to `README.md` about how the two are related?

**Comment by jhasse** [comment]
IMHO it would even make more sense to merge the two projects, see https://github.com/jcs/no_color/issues/28.

**Comment by jonasbn** [comment]
The Rust crate [colored](https://crates.io/crates/colored) support both  `NO_COLOR` and `CLICOLOR` (and `CLICOLOR_FORCE`). The documentation however lacks a clarification on how the two standards interact, so I did some [basic testing](http://jonasbn.github.io/til/crates/colored.html).

My conclusion was that in the [colored](https://crates.io/crates/colored) implementation the two can live side by side, the precedence is as follows:

1. `CLICOLOR_FORCE`
2. `NO_COLOR`
3. `CLICOLOR`

I have created [a PR](https://github.com/mackwic/colored/pull/98) with [colored](https://crates.io/crates/colored), which has not been merged yet.

Perhaps you could outline/document your recommendations on this topic from the perspective of your standard. I think the implementation in [colored](https://crates.io/crates/colored) makes sense.

**Comment by HorlogeSkynet** [comment]
> My conclusion was that in the [colored](https://crates.io/crates/colored) implementation the two can live side by side, the precedence is as follows:
> 
>     1. `CLICOLOR_FORCE`
>     2. `NO_COLOR`
>     3. `CLICOLOR`

Exactly what I ended up implementing too @jonasbn, see my comment on [jcs/no_color#28](https://github.com/jcs/no_color/issues/28#issuecomment-835407704). Cheers

**Comment by twpayne** [comment]
No response from the repo owner in over a year, so closing.
