### ISSUE TITLE
Clarify behavior of empty CLICOLOR and CLICOLOR_FORCE 

### ISSUE THREAD

**Issue by bradking** [jhasse/clicolors#8]
The specification does not currently say anything about semantics for `CLICOLOR=` and `CLICOLOR_FORCE=`.  The example code for `CLICOLOR_FORCE` implies that `CLICOLOR_FORCE=` should be equivalent to `CLICOLOR_FORCE=1`, but IMO that is confusing.  An empty setting should be equivalent to no setting at all.

**Comment by jhasse** [comment]
I would prefer empty meaning "unset", too. Unfortunately that's not how Apple implemented it :(
<img width="261" alt="image" src="https://user-images.githubusercontent.com/80071/117334123-eaf3af00-ae99-11eb-9abc-4a13565aac26.png">
Apple is probably the biggest supporter of this "spec". Maybe we can ask them somehow? Or just clarify the documentation.

**Comment by bradking** [comment]
I suggest we update the documentation to state that behavior for the empty case is unspecified so that tools can do either and users are encouraged to always set it with `0` or `1` explicitly.

**Comment by mawillers** [comment]
> [...] behavior for the empty case is unspecified [...]

Would be fine for me.

> $ CLICOLOR_FORCE=0 ls | cat
> [colored output]

Apple is really ignoring the value of that variable altogether? That goes quite against the whole idea...

**Comment by lionkor** [comment]
Hate to be that guy, especially after this long, but CLICOLOR_FORCE was only ever meant to force ENABLE colors, not force DISABLE colors. It exists because while CLICOLOR enables colors, it should still not output any colors if the output is not a TTY. Therefore, _FORCE was invented.
